
jwt:
  access_token_secret: e1bHH8TOaXTEdgMvqthopetOPT6mmxIzlkEFCtG0sgo=--fohiJWz8ByJ3rYnxkyep0w==
  refresh_token_secret: 6ZpBwC2QxYMj8z9u1HnIRYz0BEGb5R3s5B3nxQtrrOk=--USNYOGk9AtR6riTaGhjJbA==

swagger:
  username: e7jCeYwaw1cLOfP6b7A0qvKrKYYG6ozSflmJ8/L4Q3g=--8lT/diyNksUr5+8yLlgbWg==
  password: QVPnaF5KnWovWrHve4eDWl9pBBYaiAO1CehqagDSuhw=--D4pwTM+xmWAMOjdNSGBABQ==

database:
  name: R04CSLkaca+A/NfRl8FzCQsblrFq69rVVwWXNV3JSPI=--0gYWURqTid4lZ+MkmQx7wg==
  host: jxoMdPmlRReqhY+QueLPww==--AXhWYkFX++KD5XCcrme+zA==
  username: Hb+/4Z/w0lnpu+ufaUkF7A==--BUqyiqtg3/NSQl/aCqj7rw==
  password: f497f4KVwwn9EC/Wlc1A3Q==--Wb7oaa4bL5gZ4/xzeQzdIQ==
  port: WYI9CPcxggG8OD1OLP+utA==--g4bSfWd8GDflbrOqayWPmA==

emailLogin:
  tables: RXydd/STTZ98ANTI0MH7Kg==--225BAlXbKiZXQTxsSAbO1w==
  passwordMinLength: XMsVw971aZJ/NH6lD75NdQ==--lP3q0a5CeXnrIBrOoZmH5Q==
  rememberFor: FuqhVqMUWV/YwUXparLvIA==--I3bsPnT6u02laZdvL1HMjw==
  resetPasswordWithin: bRAXRvVOkGfdoal327ZSQw==--7sp8Zb5IX89HOml72BaRlw==
  maximumRetries: ltvzGtKXmxIgDMhjjygkOg==--7kCQl/Ii43tFXzm/I6YNVA==
  unlockIn: sPsYZHO2Conp1KNPvTA/rw==--g2yccFMfVWSRs8ERVSTy3g==
  passwordRegex: DEY2beZwLneIt8rIgaFhEHEhJVMFqD1PG1EWjjEkYhdBcFjANOHE2V9Fe4UuwpRJx8JFVNVKM9rqx5GAZnRPmcoUaBlvd+vNrL9eFomJ5bU=--N75lwEpBfrIMh0ZFX5S7aA==


