
jwt:
  access_token_secret: 2bDGEFVdWd8INtDms3/5dCpS+aje3xVI01+lCYvPWI8=--PpcXLe4NevKXfW57GaNmvg==
  refresh_token_secret: srpS25Ubl7U7O3TD67KB9x0pHPa9ArbjaSmXVLtFVco=--NGnlpzSCsBdd9F1ENh5T4w==

swagger:
  username: joFKbzU7dvl0D31qbx+1v1tVQQt4oQbkcIvZIv7wMXo=--IEh5o2PhCi5uy2rs4z+tLA==
  password: FZ1XKWub0UJbJzASqQtmvsPFwMKxXBaGVmMwZ2nEMjc=--q/1CCo3/a5fJMB/jGPgNvA==

database:
  name: eT65ocue/rDopU1qi2HmAphkUvcQlXGy7O+f0IfWJw4=--SCctAiKMVfTnApKfZlxHww==
  host: 1jKezsJs5A9tFGdXr+GMUw==--KkwVVQDZglUivpayOjdWAQ==
  username: 3hDjsQNqlfmnbSbsfYhbcg==--uz6KIO5Z85rjf5y5kDQzIA==
  password: zvDsBUSlr7G1su9CA5HZwA==--96kd8mPn7meQV7dcZTTxfA==
  port: 5NPu3+IZG6q5x0WqPLYvQg==--XvyGP1jjazHdROV1Au+5Ng==

emailLogin:
  tables: /oi8z/CRhuqMAY/DCmtVKg==--FU/Nfx6lx5z8y3nkpuj0jg==
  passwordMinLength: 0WTaIU4jsPWz2e+vK72vbA==--rcIkoZuwgi//IUO4R8PygA==
  rememberFor: I9hfmw8cqCJmIGzpqXaFjQ==--kLORU2CyB7oyzKt/f4JTwQ==
  resetPasswordWithin: X+xH/C3l+GXsnogP7K+arA==--kVm4Pv0i+xmumy4ckpW4OQ==
  maximumRetries: Evljg6SsMH0Jq46KY6AcSg==--08M2gHwzQUosqYRiAieSIg==
  unlockIn: D3b22op4gLt32WraLCKCpg==--q6btwXRuctMAgV9pngNecA==
  passwordRegex: tAXg/EkaWZFz8rOHe2MpcrI6/wF8VLlAMPClRBSNNMwHDf1zrPlf1woaopFclp6hlvnBdDAtJTSMqGv+X1dxo8rKgmz8/ND6jAoLR6j/1eo=--m1yHhcrmLE3EA01OadlbvQ==


